/* ─────────────────────────────────────────────────────────
 * ROMANIAN WORD LIST — auto-generated, do not edit by hand.
 *
 * ANSWERS (1046): the curated daily/practice answer pool — common,
 *   recognizable 5-letter words, re-diacriticized + quality-audited.
 * EXTRA_GUESSES (5847): additional accepted guesses, so any real
 *   Romanian word can be played, not just answers. Sourced from the
 *   official Romanian hunspell spellcheck dictionary (Rospell /
 *   dexonline, via LibreOffice), filtered to lowercase 5-letter
 *   words with correct diacritics. Real words only — no generated text.
 * Every answer is also a valid guess.
 * ───────────────────────────────────────────────────────── */

export const ANSWERS: readonly string[] = [
  'raliu', 'picat', 'triaj', 'golan', 'prins', 'albit', 'grele', 'surâs',
  'latră', 'colaj', 'punte', 'nevoi', 'croia', 'nufăr', 'picur', 'creșe',
  'uitat', 'plină', 'cavou', 'marea', 'moped', 'pătat', 'scală', 'jantă',
  'dansa', 'facil', 'fript', 'faună', 'fiert', 'eșuat', 'ovare', 'voleu',
  'larvă', 'cabla', 'naivă', 'tunat', 'creat', 'ataca', 'plâns', 'stână',
  'sedat', 'mutră', 'murat', 'lemne', 'mango', 'dilua', 'calma', 'stres',
  'ghimp', 'omorâ', 'polen', 'letal', 'vomit', 'adăpa', 'deloc', 'acizi',
  'prime', 'aurit', 'acidă', 'abilă', 'halva', 'minat', 'trufă', 'ploua',
  'halat', 'șoric', 'crăpa', 'bombă', 'pocni', 'pușcă', 'sunet', 'caste',
  'tibie', 'morți', 'coate', 'tarlă', 'testa', 'mouse', 'oprit', 'filon',
  'pilon', 'turat', 'temut', 'barză', 'oarbă', 'roșie', 'normă', 'hamac',
  'găsit', 'canin', 'parcă', 'emana', 'uimit', 'umbră', 'furat', 'părți',
  'sfere', 'eroda', 'dărui', 'nazal', 'aurie', 'acela', 'stele', 'liman',
  'rampă', 'uzură', 'rodie', 'doină', 'coral', 'iubit', 'elevă', 'piept',
  'jucat', 'fulgi', 'topit', 'masaj', 'cărți', 'abate', 'aboli', 'abona',
  'acasă', 'acces', 'aceea', 'acele', 'acest', 'acolo', 'acord', 'activ',
  'actor', 'acuza', 'adânc', 'adaos', 'adică', 'admis', 'adora', 'aduce',
  'adult', 'aduna', 'afară', 'afuma', 'agăța', 'agita', 'agrea', 'ajuta',
  'albie', 'album', 'albuș', 'alege', 'aliaj', 'alina', 'aloca', 'altar',
  'aluat', 'alună', 'amăgi', 'amâna', 'amurg', 'amuza', 'anexă', 'anima',
  'antic', 'anula', 'anume', 'anunț', 'apăra', 'apăsa', 'apuca', 'apune',
  'aramă', 'arăta', 'arcuș', 'argou', 'aripă', 'aromă', 'asalt', 'așeza',
  'aspru', 'asuma', 'atare', 'atașa', 'atent', 'atlas', 'atlet', 'audia',
  'autor', 'avans', 'avânt', 'avere', 'avion', 'bagaj', 'băiat', 'balet',
  'balon', 'baltă', 'banal', 'bancă', 'bandă', 'bănui', 'baraj', 'barbă',
  'barcă', 'bârfi', 'bazin', 'belea', 'beton', 'bidon', 'bilet', 'birou',
  'bivol', 'bizon', 'blama', 'blană', 'blând', 'bloca', 'blond', 'bluză',
  'boabă', 'boală', 'boboc', 'bogat', 'boier', 'boltă', 'bornă', 'botez',
  'breșă', 'briză', 'broda', 'bronz', 'brusc', 'bubui', 'buclă', 'bufet',
  'bufni', 'bufon', 'buget', 'bujie', 'bunic', 'bursă', 'burtă', 'buton',
  'butuc', 'cablu', 'cacao', 'cădea', 'cadou', 'cadru', 'cafea', 'caiet',
  'câine', 'călca', 'calup', 'cămin', 'campa', 'canal', 'canoe', 'cânta',
  'capac', 'capăt', 'capot', 'capră', 'carie', 'carne', 'cârpă', 'carte',
  'cască', 'căști', 'catâr', 'cățel', 'către', 'cătun', 'căuta', 'cauză',
  'ceafă', 'ceapă', 'ceară', 'ceață', 'ceaun', 'cerne', 'cerși', 'certa',
  'cețos', 'cheie', 'chema', 'chiar', 'chilă', 'chior', 'chist', 'ciclu',
  'cifră', 'cinci', 'cinic', 'circa', 'citeț', 'ciudă', 'ciumă', 'ciupi',
  'civil', 'cizmă', 'clădi', 'clamă', 'clasă', 'climă', 'clipă', 'clipi',
  'clovn', 'coace', 'coadă', 'coajă', 'coamă', 'coasă', 'coase', 'cocor',
  'cocoș', 'codaș', 'coleg', 'comic', 'comod', 'comun', 'conta', 'conte',
  'copac', 'copia', 'copie', 'copii', 'copil', 'copoi', 'covor', 'crede',
  'cremă', 'creșă', 'cretă', 'crimă', 'criză', 'cruce', 'crunt', 'cruța',
  'cufăr', 'cuget', 'cuier', 'culca', 'cules', 'culme', 'cumva', 'cupla',
  'cuplu', 'curaj', 'curat', 'curbă', 'curea', 'curge', 'cursă', 'curte',
  'cusur', 'cutie', 'daltă', 'dativ', 'dator', 'daună', 'debil', 'debut',
  'deces', 'decis', 'decor', 'deget', 'dejun', 'deltă', 'desen', 'devia',
  'dicta', 'dietă', 'difuz', 'dineu', 'dinte', 'divin', 'docil', 'doică',
  'dolar', 'doliu', 'dormi', 'dosar', 'dramă', 'drapa', 'drept', 'dronă',
  'dubiu', 'duios', 'dulap', 'dulce', 'dungă', 'dușcă', 'echer', 'ecran',
  'edita', 'educa', 'efect', 'efort', 'elice', 'emite', 'enorm', 'epavă',
  'epocă', 'eroic', 'etala', 'etanș', 'etapă', 'evada', 'evita', 'exact',
  'exces', 'faclă', 'faimă', 'făină', 'falcă', 'fantă', 'faptă', 'farsă',
  'fatal', 'făuri', 'fazan', 'febră', 'felie', 'fermă', 'festă', 'ficat',
  'fidel', 'fiere', 'fiică', 'final', 'firav', 'firmă', 'fizic', 'floră',
  'flotă', 'fluid', 'foaie', 'foiță', 'folos', 'fontă', 'forja', 'formă',
  'forță', 'frână', 'frate', 'freca', 'frică', 'frige', 'front', 'fruct',
  'fugar', 'fular', 'funie', 'furcă', 'furie', 'fustă', 'găină', 'galon',
  'galop', 'gambă', 'garaj', 'gardă', 'gașcă', 'gaură', 'găuri', 'gazdă',
  'geană', 'gelos', 'geniu', 'ghici', 'ghips', 'glugă', 'glumă', 'goană',
  'grabă', 'grăbi', 'grajd', 'grava', 'grefă', 'greoi', 'grevă', 'grijă',
  'grilă', 'gripă', 'grotă', 'guler', 'gunoi', 'haină', 'haine', 'haită',
  'hamal', 'hartă', 'holba', 'hotar', 'hotel', 'hrană', 'hrăni', 'iarbă',
  'iarnă', 'ibric', 'ideal', 'idilă', 'ierta', 'imens', 'imita', 'impar',
  'înalt', 'încet', 'îndoi', 'infam', 'înger', 'inimă', 'întâi', 'intim',
  'intra', 'între', 'învoi', 'irita', 'irosi', 'isteț', 'iulie', 'iunie',
  'izola', 'izvor', 'jefui', 'jeleu', 'jigni', 'jilav', 'joacă', 'joben',
  'județ', 'jurat', 'juriu', 'lacăt', 'lacom', 'lalea', 'lampă', 'lance',
  'lângă', 'lansa', 'lapte', 'lărgi', 'larmă', 'laser', 'latin', 'laudă',
  'leafă', 'legal', 'leneș', 'leșin', 'liber', 'liceu', 'lider', 'limbă',
  'linie', 'linte', 'lipsă', 'liric', 'listă', 'litru', 'livra', 'locui',
  'logic', 'loial', 'lucid', 'luciu', 'lucra', 'lucru', 'lunar', 'luptă',
  'măcar', 'măgar', 'magic', 'magie', 'mâhni', 'maică', 'mâine', 'maior',
  'major', 'mânca', 'mâner', 'mânia', 'manie', 'mânji', 'manta', 'mânui',
  'mârâi', 'marcă', 'maree', 'măreț', 'marfă', 'marți', 'mască', 'măsea',
  'masiv', 'matcă', 'matur', 'maxim', 'medic', 'medie', 'mediu', 'menaj',
  'mereu', 'merge', 'merit', 'mesaj', 'metal', 'miere', 'milos', 'minge',
  'minim', 'minor', 'minte', 'minți', 'minus', 'minut', 'miros', 'mișca',
  'moale', 'moară', 'mobil', 'model', 'molie', 'monta', 'moral', 'morar',
  'moșie', 'motiv', 'motor', 'muget', 'mugur', 'mulge', 'mumie', 'muncă',
  'munte', 'muscă', 'muzeu', 'nămol', 'nărav', 'naște', 'natal', 'nebun',
  'necaz', 'negru', 'nepot', 'neted', 'nimic', 'ninge', 'nisip', 'niște',
  'nivel', 'nobil', 'nociv', 'noroc', 'noroi', 'numai', 'număr', 'nuntă',
  'nutri', 'oaste', 'oblon', 'obosi', 'obraz', 'ocară', 'ocean', 'ocupa',
  'odată', 'odios', 'oferi', 'ofili', 'omidă', 'omite', 'onest', 'onora',
  'operă', 'optim', 'opune', 'ordin', 'orfan', 'organ', 'orice', 'ospăț',
  'ostaș', 'ostil', 'păcat', 'pâclă', 'păgân', 'pahar', 'pâine', 'palat',
  'palid', 'palmă', 'panou', 'pantă', 'pânză', 'papuc', 'pârâu', 'părea',
  'paria', 'paroh', 'parte', 'pasaj', 'pasiv', 'pastă', 'paște', 'patru',
  'pauză', 'penar', 'penel', 'peria', 'perlă', 'pernă', 'peron', 'pește',
  'petic', 'piață', 'picta', 'piele', 'pieri', 'piesă', 'pildă', 'pilot',
  'pipăi', 'piper', 'pirat', 'piron', 'pișca', 'pisoi', 'pistă', 'pitic',
  'placă', 'plajă', 'plana', 'plasă', 'plată', 'plăti', 'pleca', 'pleda',
  'plisc', 'plivi', 'plumb', 'plută', 'poală', 'poate', 'podea', 'podiș',
  'poftă', 'pojar', 'polei', 'polua', 'pompă', 'ponei', 'popor', 'porni',
  'posac', 'poștă', 'potop', 'pradă', 'prăji', 'prânz', 'preda', 'preot',
  'presă', 'preta', 'primi', 'prinț', 'pripă', 'priva', 'privi', 'priză',
  'probă', 'prost', 'proză', 'prună', 'prund', 'pudră', 'puhoi', 'pulsa',
  'punct', 'pungă', 'purta', 'putea', 'puțin', 'răbda', 'râcâi', 'răcni',
  'radio', 'răgaz', 'raion', 'rămas', 'rapid', 'ratat', 'rație', 'raton',
  'răzui', 'rebel', 'regal', 'regla', 'releu', 'relua', 'reper', 'rețea',
  'reuni', 'reuși', 'rigid', 'riglă', 'rival', 'roade', 'roată', 'robot',
  'roman', 'rosti', 'rugbi', 'ruina', 'rundă', 'ruptă', 'rural', 'sabie',
  'sâcâi', 'salam', 'sălta', 'salut', 'salva', 'sânge', 'sanie', 'șansă',
  'șapcă', 'șapte', 'săpun', 'sărac', 'sarma', 'șarpe', 'sărut', 'scalp',
  'scăpa', 'scară', 'scaun', 'scenă', 'sclav', 'scobi', 'scrie', 'scrum',
  'scuar', 'scula', 'scump', 'scund', 'scurt', 'scuti', 'scuza', 'seară',
  'secat', 'secol', 'ședea', 'seism', 'semeț', 'senin', 'serba', 'serie',
  'șerif', 'servi', 'sever', 'sezon', 'sfânt', 'sferă', 'sfert', 'sfida',
  'sifon', 'sigur', 'șiret', 'șiroi', 'sirop', 'situa', 'slăbi', 'slavă',
  'soare', 'soclu', 'socru', 'șofer', 'solar', 'solid', 'sondă', 'sonet',
  'sonor', 'șopti', 'sorbi', 'sorți', 'șosea', 'șovăi', 'spăla', 'spate',
  'spera', 'spion', 'spirt', 'spiță', 'spori', 'sport', 'spumă', 'spune',
  'stâlp', 'stand', 'stâng', 'stare', 'staul', 'steag', 'stemă', 'stimă',
  'stins', 'știre', 'stivă', 'stofă', 'strat', 'strop', 'subit', 'șuetă',
  'sufla', 'sumar', 'șuncă', 'suplu', 'sursă', 'șurub', 'șuvoi', 'tabel',
  'tablă', 'tăcea', 'tăcut', 'taină', 'talie', 'tânăr', 'tânji', 'tapet',
  'tărâm', 'țăran', 'tărie', 'tarif', 'tartă', 'țăruș', 'țâșni', 'tătic',
  'tavan', 'teacă', 'teamă', 'teanc', 'țeavă', 'tenis', 'terci', 'teren',
  'ticsi', 'țiglă', 'tigru', 'tihnă', 'timid', 'tinde', 'țintă', 'ținut',
  'tipar', 'tipic', 'tiran', 'țiței', 'titlu', 'toiag', 'topăi', 'topor',
  'torță', 'trăda', 'trage', 'trata', 'treaz', 'trece', 'trișa', 'trist',
  'trudă', 'trupă', 'tunde', 'tunel', 'turba', 'turlă', 'turmă', 'turna',
  'uliță', 'ultim', 'umbla', 'umbre', 'umfla', 'umple', 'unchi', 'unghi',
  'urban', 'uriaș', 'ursuz', 'ușura', 'uzină', 'văduv', 'vagon', 'văita',
  'valet', 'valid', 'vapor', 'vargă', 'varia', 'vărsa', 'vărui', 'varză',
  'vâslă', 'vatră', 'vechi', 'vecie', 'vecin', 'vedea', 'veghe', 'venin',
  'venit', 'verde', 'vervă', 'vesel', 'vestă', 'veste', 'viață', 'vibra',
  'vicia', 'vifor', 'vinde', 'virus', 'vișin', 'vital', 'vițel', 'vlagă',
  'voiaj', 'voios', 'volan', 'volei', 'volum', 'vorbă', 'vrajă', 'vrăji',
  'vreme', 'vulpe', 'zadar', 'zahăr', 'zarvă', 'zăvor', 'zbura', 'zeamă',
  'zebră', 'zefir', 'zeiță', 'zgură', 'zodie', 'zvelt',
]

const EXTRA_GUESSES: readonly string[] = [
  'abacă', 'abată', 'abați', 'abced', 'abces', 'abdic', 'abduc', 'abhor', 'abjur', 'abneg',
  'abraș', 'abrog', 'aburc', 'abzic', 'abătu', 'abție', 'abții', 'abțin', 'abțiu', 'acaju',
  'acced', 'acciz', 'aceia', 'acerb', 'aceră', 'achit', 'achiu', 'acira', 'aciră', 'aclam',
  'acnee', 'acont', 'acort', 'acrit', 'acriș', 'acruț', 'acuma', 'acută', 'acuză', 'acușa',
  'acuși', 'adaog', 'adape', 'adapi', 'adapă', 'adast', 'adaug', 'adaus', 'adept', 'adiai',
  'adiam', 'adiat', 'adiau', 'adiem', 'adjur', 'admin', 'admir', 'admit', 'adnat', 'adopt',
  'adorm', 'aduct', 'adusă', 'advon', 'adăpe', 'adăpi', 'adăpă', 'adăst', 'aeraj', 'aerat',
  'aerez', 'aerob', 'aeros', 'afara', 'afect', 'affix', 'afgan', 'afidă', 'afină', 'afion',
  'afipt', 'afirm', 'aflat', 'aflux', 'afonă', 'aftos', 'afund', 'afurc', 'afâna', 'agapă',
  'agată', 'agavă', 'agațe', 'agață', 'agent', 'agest', 'agilă', 'agnat', 'agneț', 'agonă',
  'agora', 'agoră', 'agrar', 'agriș', 'agudă', 'aguti', 'agățe', 'agăți', 'agăță', 'aicea',
  'aiept', 'aiest', 'aiste', 'aistă', 'aișor', 'aiști', 'ajung', 'ajuns', 'alait', 'alama',
  'alamo', 'alamă', 'alaun', 'albeț', 'albia', 'albii', 'albiu', 'albui', 'albuț', 'alcan',
  'alcov', 'aldan', 'aldin', 'aldol', 'alean', 'aleea', 'aleii', 'alelă', 'alenă', 'alerg',
  'alert', 'aleză', 'algic', 'algid', 'algie', 'algol', 'alias', 'aliat', 'alibi', 'alică',
  'aliez', 'alint', 'alior', 'almar', 'almee', 'aloea', 'aloei', 'alpin', 'altei', 'altoi',
  'altor', 'altui', 'altul', 'alung', 'aluni', 'alură', 'alămi', 'alții', 'amant', 'amară',
  'ambar', 'ambii', 'ambră', 'ament', 'amibă', 'amidă', 'amino', 'amină', 'amnar', 'amorf',
  'amper', 'amplu', 'amplă', 'amuța', 'amuțe', 'amuță', 'amvon', 'anală', 'ancie', 'andin',
  'anglo', 'angro', 'anime', 'anion', 'anost', 'antal', 'antet', 'antum', 'anual', 'anuar',
  'anură', 'anșoa', 'aoleo', 'aoleu', 'aortă', 'apare', 'apari', 'apară', 'apasă', 'apere',
  'aperi', 'apese', 'apeși', 'apidă', 'apiol', 'aplat', 'aplec', 'aplet', 'aplic', 'aplit',
  'apnee', 'apodă', 'aport', 'apret', 'aprig', 'april', 'aprob', 'aprod', 'aprox', 'apter',
  'apuci', 'apupa', 'apupă', 'apăru', 'apără', 'apăsă', 'arabă', 'arama', 'aramo', 'arare',
  'arate', 'arată', 'arbiu', 'arbor', 'arbuz', 'arcan', 'arcat', 'arcaș', 'ardea', 'ardei',
  'ardic', 'areal', 'areic', 'arenă', 'arest', 'areta', 'aretă', 'argat', 'argea', 'argon',
  'argus', 'argut', 'arhar', 'arhon', 'arian', 'arici', 'aridă', 'arină', 'aripa', 'aripi',
  'aripo', 'arman', 'armar', 'armat', 'armaș', 'armez', 'armie', 'armân', 'arsei', 'arsen',
  'artel', 'artos', 'arunc', 'arval', 'arvat', 'arătă', 'arăți', 'arșic', 'arșin', 'arțag',
  'arțar', 'ascet', 'ascii', 'ascut', 'asert', 'asiat', 'asină', 'asist', 'asiză', 'asmut',
  'asoma', 'aspic', 'aspir', 'aspri', 'aspră', 'astea', 'astei', 'aster', 'astmă', 'astru',
  'astră', 'astup', 'async', 'atelă', 'aterm', 'atest', 'ating', 'atins', 'atlaz', 'atomă',
  'atonă', 'atrag', 'atras', 'atriu', 'atuul', 'atârn', 'atâta', 'atâtă', 'atâți', 'audio',
  'audit', 'augur', 'auire', 'auită', 'aulic', 'aurar', 'aurel', 'auric', 'auriu', 'auros',
  'auzea', 'auzii', 'auzim', 'auzit', 'aușel', 'avaet', 'avară', 'aveai', 'aveam', 'aveau',
  'avenă', 'avers', 'aveți', 'aviar', 'avidă', 'avizo', 'avort', 'avram', 'avuez', 'avură',
  'avuse', 'avută', 'avuși', 'având', 'axare', 'axată', 'axial', 'axilă', 'axion', 'azeră',
  'azidă', 'azimă', 'azoic', 'aztec', 'azuri', 'așază', 'așezi', 'așeză', 'ațică', 'aține',
  'aținu', 'ațină', 'babac', 'baban', 'babau', 'babit', 'baboi', 'bacal', 'bacil', 'badea',
  'badei', 'baftă', 'bagea', 'bahic', 'bahnă', 'baian', 'baier', 'balaș', 'balic', 'balie',
  'balot', 'balsa', 'balta', 'balto', 'balâc', 'banan', 'banat', 'banca', 'banco', 'banda',
  'bando', 'banjo', 'banta', 'bantu', 'bantă', 'barat', 'barba', 'barbo', 'barca', 'barco',
  'barda', 'bardo', 'bardă', 'barem', 'barez', 'baric', 'barie', 'baril', 'barim', 'bariu',
  'bariz', 'bariș', 'barjă', 'baroc', 'baron', 'baros', 'barou', 'barza', 'barzo', 'bască',
  'baset', 'basic', 'basma', 'basnă', 'bason', 'basta', 'bataj', 'batal', 'batat', 'batav',
  'batcă', 'batem', 'batic', 'batir', 'batiu', 'batoc', 'batog', 'baton', 'baune', 'bazal',
  'bazar', 'bazat', 'bazez', 'bazic', 'bazon', 'bașcă', 'baștă', 'beata', 'beată', 'beați',
  'becar', 'becer', 'behăi', 'belit', 'bemol', 'beniș', 'bente', 'benzi', 'benți', 'berar',
  'berat', 'berce', 'berci', 'bercă', 'beret', 'beril', 'bermă', 'bernă', 'bertă', 'berze',
  'betei', 'betel', 'beucă', 'beuță', 'bezea', 'beznă', 'beând', 'beșic', 'beție', 'beții',
  'bețiv', 'biata', 'biato', 'biată', 'biban', 'biber', 'bibic', 'bibil', 'bideu', 'bielă',
  'biete', 'bietă', 'bifat', 'bifer', 'bifez', 'bifid', 'bigam', 'bigii', 'bigot', 'bijoi',
  'bilon', 'biman', 'binar', 'bingo', 'biniș', 'binom', 'bintă', 'bipal', 'biped', 'bipen',
  'birar', 'birjă', 'birău', 'bisat', 'bisel', 'bisez', 'biter', 'bitum', 'biută', 'bizam',
  'bizar', 'bizeț', 'bizou', 'bizui', 'blade', 'blana', 'blanc', 'blano', 'blază', 'bleah',
  'bleau', 'bleav', 'bleot', 'bleul', 'blimp', 'blitz', 'bloat', 'blues', 'blugi', 'blăni',
  'boacă', 'boala', 'boalo', 'boare', 'boașă', 'boață', 'bober', 'bobit', 'bobot', 'bocal',
  'bocet', 'bocit', 'bocnă', 'bocși', 'bocșă', 'boemă', 'boire', 'boită', 'bojoc', 'bojog',
  'bolfă', 'bolid', 'bolii', 'bolit', 'bolta', 'bolto', 'bolți', 'bonom', 'bontă', 'bonus',
  'boran', 'borat', 'borax', 'bordo', 'boric', 'borii', 'bortă', 'borză', 'borât', 'bosaj',
  'boson', 'bossa', 'botcă', 'botei', 'botos', 'botoș', 'bouar', 'bovid', 'bovin', 'boxat',
  'boxer', 'boxez', 'boxul', 'bozie', 'bozon', 'boșar', 'boșii', 'boțit', 'braga', 'bragă',
  'braha', 'brahe', 'brahă', 'bramă', 'brand', 'branț', 'bravă', 'breaz', 'breji', 'brevă',
  'breze', 'briat', 'brici', 'brică', 'bridă', 'briez', 'broșă', 'bruft', 'brumă', 'brună',
  'brută', 'brâie', 'brână', 'brâul', 'brăgi', 'btrfs', 'bubal', 'bubat', 'buboi', 'bubon',
  'bubos', 'bucal', 'bucar', 'bucea', 'buche', 'buchi', 'bucin', 'bucle', 'bucur', 'bucșă',
  'budat', 'budez', 'budăi', 'bufan', 'bufeu', 'bufnă', 'buged', 'buglă', 'buhai', 'buhav',
  'buhnă', 'buhos', 'buhur', 'buiac', 'buire', 'buită', 'bujdă', 'bujor', 'bulat', 'bulcă',
  'bulet', 'bulin', 'bulon', 'buluc', 'bundă', 'bunel', 'bunuț', 'buraj', 'burat', 'burbă',
  'burcă', 'buret', 'burez', 'buric', 'burin', 'buriu', 'burta', 'burto', 'burți', 'butac',
  'butan', 'butar', 'butaș', 'butcă', 'butic', 'butie', 'butoi', 'butur', 'buzat', 'buzer',
  'buzna', 'buzoi', 'buzău', 'bușel', 'bușeu', 'bușit', 'bușon', 'bâcâi', 'bâlci', 'bându',
  'bârfă', 'bârnă', 'bârsă', 'bâzoi', 'bâzâi', 'bâțan', 'bâțâi', 'băbit', 'băboi', 'băcan',
  'băcit', 'bădia', 'bădic', 'bădie', 'bădii', 'băgai', 'băgam', 'băgat', 'băgau', 'băgăm',
  'băiaș', 'băiet', 'băieș', 'băiță', 'bălai', 'bălan', 'băleg', 'bălos', 'băluț', 'bălți',
  'bănat', 'bănci', 'bănet', 'bănie', 'bănit', 'bănos', 'bănuț', 'bărat', 'bărbi', 'bărci',
  'bărzi', 'băsma', 'bătea', 'bătui', 'bătut', 'bătăi', 'băune', 'băuni', 'băură', 'băuse',
  'băută', 'băuși', 'bășic', 'bățos', 'bățul', 'cabaz', 'cacic', 'cacom', 'cadet', 'cadiu',
  'cadră', 'caduc', 'cadus', 'cafas', 'cafer', 'cafru', 'cahlă', 'caiac', 'caier', 'caisă',
  'calaj', 'calao', 'calat', 'calce', 'calci', 'calcă', 'caldă', 'calea', 'calem', 'calez',
  'calfă', 'calic', 'calif', 'calin', 'calmă', 'calos', 'calpă', 'calul', 'calus', 'camee',
  'canaf', 'canar', 'canat', 'canci', 'canea', 'canga', 'cange', 'cangă', 'canid', 'caniș',
  'canon', 'canto', 'capan', 'caper', 'capeș', 'capie', 'capoc', 'capon', 'capsă', 'carab',
  'caras', 'carat', 'cardă', 'carea', 'caret', 'careu', 'cargo', 'caria', 'caric', 'carou',
  'carst', 'cartă', 'carub', 'carăm', 'casap', 'casat', 'casca', 'casez', 'casiu', 'castă',
  'catar', 'catod', 'caute', 'caută', 'cauți', 'cavaf', 'caval', 'cavas', 'cavet', 'cazac',
  'cazan', 'cazat', 'cazez', 'cazic', 'cazma', 'caznă', 'cazon', 'cașei', 'cașeu', 'caște',
  'caști', 'cațăr', 'ceafa', 'ceair', 'ceapa', 'ceara', 'ceata', 'ceato', 'ceată', 'ceauș',
  'ceața', 'ceațo', 'cecal', 'cecen', 'cecum', 'cedat', 'cedez', 'cedru', 'cefar', 'cefei',
  'cehit', 'celar', 'celea', 'cella', 'celle', 'cello', 'celom', 'celtă', 'cenur', 'cepei',
  'cepse', 'cerat', 'cerea', 'cerem', 'cerga', 'cergi', 'cergo', 'cergă', 'cerii', 'cerit',
  'ceriu', 'ceros', 'certe', 'certă', 'cerui', 'cerut', 'cerți', 'cesiu', 'cestă', 'cetaș',
  'cetei', 'ceter', 'ceteț', 'cetit', 'ceucă', 'cezar', 'cești', 'ceții', 'chaos', 'cheag',
  'chele', 'cheli', 'chelă', 'cheme', 'chemi', 'chemă', 'chera', 'chere', 'chesă', 'chetă',
  'chibz', 'chică', 'chiot', 'chiui', 'chiul', 'chiup', 'chulo', 'cicar', 'cidru', 'cifos',
  'cifru', 'cimen', 'cinat', 'cinel', 'cinez', 'cinge', 'cingă', 'ciomp', 'ciont', 'ciori',
  'cipic', 'cipru', 'cirac', 'circă', 'cireș', 'ciriș', 'cirtă', 'cirus', 'cislă', 'cistă',
  'citat', 'citez', 'citit', 'ciuin', 'ciulă', 'ciump', 'ciung', 'ciunt', 'ciută', 'civic',
  'civit', 'claca', 'clacă', 'cladă', 'claie', 'clanc', 'clanț', 'clapă', 'clară', 'class',
  'clean', 'clemă', 'clică', 'cling', 'clint', 'clină', 'clips', 'clisă', 'clonc', 'clonă',
  'clonț', 'cloță', 'clupă', 'clăci', 'clăit', 'cneaz', 'cneji', 'cnezi', 'coacă', 'coada',
  'coado', 'coafă', 'coaja', 'coajo', 'coala', 'coalo', 'coală', 'coană', 'coati', 'coată',
  'cobai', 'cobea', 'cobei', 'cobit', 'cobor', 'cobră', 'cobur', 'cobuz', 'cobză', 'cocal',
  'cocea', 'cocie', 'cocon', 'cocos', 'cocoț', 'codaj', 'codal', 'codan', 'codat', 'codex',
  'codez', 'codit', 'codon', 'codor', 'codoș', 'codru', 'cofei', 'coiot', 'cojii', 'cojit',
  'cojoc', 'colac', 'colan', 'colat', 'colea', 'colet', 'colez', 'colic', 'colie', 'colin',
  'colir', 'colnă', 'colon', 'color', 'colos', 'colun', 'comat', 'combi', 'combo', 'comet',
  'comis', 'comit', 'comor', 'comut', 'conac', 'conat', 'concă', 'condu', 'conex', 'coneț',
  'conga', 'conic', 'const', 'copai', 'copal', 'copan', 'copcă', 'coper', 'copră', 'coptă',
  'corai', 'coraj', 'coran', 'corbi', 'coree', 'coreu', 'coreț', 'corfă', 'corlă', 'coroi',
  'corup', 'corzi', 'cosac', 'cosar', 'cosaș', 'cosea', 'cosie', 'cosit', 'cosmo', 'cosoi',
  'cosor', 'cotar', 'cotei', 'cotez', 'coteț', 'cotil', 'cotit', 'cotiș', 'cotoi', 'cotor',
  'coviț', 'covru', 'coxal', 'cozii', 'coșar', 'coșer', 'craca', 'craco', 'cracă', 'cramă',
  'crape', 'crapă', 'crasă', 'craun', 'crază', 'credo', 'creez', 'creol', 'creps', 'cresc',
  'crezi', 'crezu', 'cridă', 'crilă', 'criță', 'croat', 'croit', 'crosă', 'croșă', 'cruci',
  'crudă', 'crupă', 'crypt', 'crâng', 'crâșc', 'crăci', 'crăie', 'crăpe', 'crăpi', 'crăpă',
  'cuart', 'cuarț', 'cubaj', 'cubez', 'cubic', 'cucii', 'cucon', 'cucui', 'cucuț', 'cuiul',
  'cuiuț', 'cuiva', 'cujbă', 'culac', 'culaj', 'culci', 'culeg', 'culic', 'culot', 'culpă',
  'cultă', 'cuman', 'cumen', 'cumul', 'cunun', 'cupaj', 'cupal', 'cupar', 'cupeu', 'cupeț',
  'cupid', 'cupit', 'cupiu', 'cuplă', 'cupon', 'cupru', 'curca', 'curci', 'curcă', 'curez',
  'curie', 'curiu', 'curma', 'curme', 'curmi', 'curmă', 'curuț', 'curvă', 'curăț', 'curți',
  'cusei', 'custa', 'custe', 'cusui', 'cusut', 'cutat', 'cuter', 'cutez', 'cutră', 'cuvie',
  'cuvin', 'cușac', 'cușaj', 'cușca', 'cușco', 'cușcă', 'cușer', 'cușmă', 'cuști', 'cuțit',
  'cvarț', 'cvasi', 'câlți', 'câner', 'cârcă', 'cârjă', 'cârmă', 'cârnă', 'cârâi', 'câtea',
  'câtor', 'câtul', 'câtva', 'câști', 'căcai', 'căcam', 'căcat', 'căcau', 'căcăm', 'cădem',
  'cădit', 'căile', 'căire', 'căită', 'căiță', 'călaf', 'călcă', 'călin', 'călit', 'căluș',
  'căluț', 'călâu', 'călâă', 'călău', 'căngi', 'cănit', 'căpos', 'căpuș', 'căpău', 'cărai',
  'căram', 'cărat', 'cărau', 'cărei', 'cărni', 'căror', 'cărui', 'căruț', 'cărăm', 'căsca',
  'căscă', 'cătai', 'cătam', 'cătat', 'cătau', 'cătur', 'cătăm', 'căulă', 'căută', 'căzii',
  'căzui', 'căzut', 'cășuț', 'cățea', 'căție', 'cățui', 'cățăi', 'dacei', 'dacic', 'dacie',
  'dacit', 'dafie', 'dafin', 'daiac', 'daică', 'dalac', 'dalaj', 'dalbă', 'dalez', 'dalia',
  'dalie', 'dalta', 'dalto', 'danci', 'dandi', 'danez', 'danga', 'danie', 'dapăr', 'darac',
  'dardă', 'darie', 'darme', 'darmă', 'dasem', 'dasie', 'datat', 'datez', 'debit', 'decad',
  'decan', 'decar', 'decid', 'decil', 'decât', 'dedai', 'dedal', 'dedam', 'dedat', 'dedau',
  'dedea', 'dedei', 'dedic', 'deduc', 'dedus', 'dedăm', 'defel', 'defer', 'degaj', 'deger',
  'deism', 'deist', 'dejoc', 'dejug', 'delas', 'delco', 'deleg', 'delir', 'deliu', 'deluț',
  'demis', 'demit', 'demiu', 'demnă', 'demon', 'demos', 'denar', 'deneg', 'denie', 'densă',
  'depou', 'depun', 'depus', 'depăn', 'depăr', 'derbi', 'derea', 'dereș', 'deriv', 'dermă',
  'derog', 'desag', 'desec', 'deset', 'desfă', 'desic', 'desiș', 'detei', 'detun', 'dever',
  'devfs', 'devii', 'devin', 'deviu', 'deviz', 'devlă', 'dezic', 'dezis', 'deșel', 'deșeu',
  'deșir', 'dețin', 'dhcpd', 'dială', 'diată', 'diblu', 'diblă', 'difer', 'diger', 'digit',
  'dihai', 'dihoc', 'dihor', 'dijmă', 'dilat', 'dimer', 'dimie', 'dinam', 'dinar', 'dindu',
  'dingo', 'dintr', 'diodă', 'dioic', 'dipod', 'dipol', 'direg', 'dires', 'disco', 'disec',
  'disip', 'ditai', 'diurn', 'divan', 'divid', 'diviz', 'doagă', 'doapă', 'doare', 'doară',
  'doasă', 'dobaș', 'dobor', 'doboș', 'dobra', 'docar', 'doctă', 'dogal', 'dogar', 'dogat',
  'dogit', 'dogmă', 'dohot', 'doiar', 'doime', 'dolby', 'dolie', 'domin', 'domol', 'domră',
  'donat', 'donez', 'donor', 'dopaj', 'dopat', 'dopez', 'dorat', 'dorea', 'doric', 'dorit',
  'dornă', 'doruț', 'dosit', 'dotal', 'dotat', 'dotez', 'doxei', 'dozaj', 'dozat', 'dozez',
  'drace', 'dracă', 'dragă', 'drelă', 'drenă', 'dreve', 'drețe', 'drops', 'drugă', 'druid',
  'drupă', 'drusă', 'druză', 'drâng', 'duală', 'duant', 'dubas', 'dubat', 'dubit', 'duble',
  'dublu', 'dublă', 'ducal', 'ducat', 'ducea', 'ducii', 'dudui', 'dudău', 'duhan', 'duhli',
  'duhni', 'duium', 'dulci', 'dulie', 'dulău', 'dumic', 'dunaj', 'dunga', 'dungi', 'dungo',
  'dupcă', 'durat', 'durdă', 'durea', 'durez', 'durit', 'durui', 'durut', 'durăt', 'dutcă',
  'dușca', 'dușco', 'duște', 'duști', 'dâlmă', 'dându', 'dânsa', 'dârez', 'dârji', 'dârza',
  'dârze', 'dârzu', 'dârză', 'dârâi', 'dârâm', 'dârât', 'dădea', 'dădui', 'dădut', 'dăgii',
  'dălii', 'dălți', 'dănos', 'dărac', 'dărma', 'dărme', 'dărmi', 'dărmă', 'dărâm', 'eboșă',
  'ecart', 'echea', 'echei', 'eclat', 'ecler', 'ectip', 'ecvin', 'edict', 'educi', 'eflux',
  'egală', 'egidă', 'ejobs', 'eleat', 'elenă', 'elici', 'elină', 'elită', 'emacs', 'email',
  'emden', 'emerg', 'emeri', 'emers', 'enara', 'enter', 'enunț', 'eocen', 'eolit', 'epodă',
  'epohă', 'eponj', 'epură', 'erată', 'erați', 'erbiu', 'erect', 'erede', 'erete', 'ergan',
  'erhei', 'erige', 'erigă', 'ermit', 'erodă', 'erupe', 'erupi', 'erupt', 'erupă', 'erzaț',
  'ester', 'estet', 'estic', 'estiv', 'eston', 'estru', 'etală', 'etate', 'etenă', 'etern',
  'etiaj', 'etică', 'etnic', 'etnie', 'etolă', 'etuvă', 'eului', 'eunuc', 'eurip', 'event',
  'evier', 'eving', 'evins', 'evreu', 'exala', 'exale', 'exali', 'exală', 'exarh', 'excit',
  'exeat', 'exige', 'exima', 'exină', 'exist', 'exisă', 'expir', 'expre', 'expun', 'expus',
  'extaz', 'extra', 'exult', 'eșapa', 'eșuaj', 'eșuez', 'facem', 'facto', 'fagot', 'fagur',
  'faină', 'falca', 'falco', 'falei', 'falet', 'falie', 'falit', 'falsă', 'falun', 'falus',
  'famat', 'famen', 'fanal', 'fanar', 'fanat', 'fanez', 'fanon', 'fante', 'farad', 'farbă',
  'farin', 'farul', 'fason', 'fastă', 'fatic', 'fatum', 'fault', 'favor', 'favus', 'fazat',
  'fazic', 'fazor', 'fdisk', 'fecal', 'feder', 'felah', 'felid', 'felin', 'felon', 'femur',
  'fenat', 'fenec', 'fenic', 'fenil', 'fenix', 'fenol', 'fentă', 'ferat', 'ferec', 'feric',
  'ferin', 'ferit', 'feros', 'ferță', 'fetal', 'fetei', 'fetid', 'fetie', 'fetit', 'fetiș',
  'fetru', 'fetus', 'feudă', 'feșei', 'feșii', 'feței', 'feții', 'fială', 'fiare', 'fiară',
  'fibră', 'ficus', 'fidea', 'fider', 'fiece', 'fierb', 'fiesc', 'fiica', 'fiice', 'fiind',
  'filaj', 'filar', 'filat', 'filer', 'filet', 'fileu', 'filez', 'filit', 'findu', 'finet',
  'finez', 'fineț', 'finic', 'finit', 'finiș', 'finuț', 'fiolă', 'fionc', 'fiong', 'fiord',
  'firet', 'firez', 'firit', 'firiz', 'firos', 'firuț', 'fitil', 'fixaj', 'fixat', 'fixez',
  'fișat', 'fișcă', 'fișet', 'fișez', 'fișic', 'fișiu', 'flamă', 'flanc', 'flaps', 'flasc',
  'flash', 'flaut', 'fleac', 'fleșă', 'flint', 'flirt', 'flori', 'fluaj', 'fluat', 'fludă',
  'fluor', 'foaia', 'foaio', 'foale', 'foame', 'fobic', 'fobie', 'focal', 'focar', 'focos',
  'focus', 'focși', 'fodră', 'foehn', 'foile', 'foios', 'foire', 'foită', 'folia', 'folie',
  'folii', 'folio', 'foliu', 'folkă', 'fondu', 'fonem', 'fonfă', 'fonic', 'fonie', 'fonon',
  'foraj', 'forat', 'foraș', 'forez', 'forjă', 'forte', 'forum', 'forăi', 'fosil', 'fostă',
  'fotel', 'foton', 'foxul', 'fraga', 'fragi', 'frago', 'fragă', 'fraht', 'franc', 'franj',
  'franș', 'frază', 'freon', 'fretă', 'frevo', 'freză', 'freșă', 'friză', 'frola', 'frupt',
  'frust', 'frâie', 'frânc', 'frâne', 'frâng', 'frânt', 'frâul', 'fstab', 'fucus', 'fudul',
  'fugea', 'fugii', 'fugim', 'fugit', 'fugos', 'fuior', 'fuleu', 'fulie', 'fumar', 'fumat',
  'fumeg', 'fumez', 'fundă', 'fungă', 'fuori', 'furaj', 'furan', 'furda', 'furiș', 'furou',
  'furăm', 'fusar', 'fusei', 'fusel', 'futea', 'futem', 'futil', 'futui', 'futut', 'fuzee',
  'fuzel', 'fuzen', 'fânar', 'fânaț', 'fâsâi', 'fâsăi', 'fâșie', 'fâșâi', 'fâșăi', 'fâțâi',
  'făcea', 'făcui', 'făcut', 'făgaș', 'făget', 'făina', 'făini', 'fălci', 'fălie', 'fălit',
  'fălos', 'făraș', 'fărâm', 'fătat', 'fătau', 'fătoi', 'fătul', 'fășie', 'fățiș', 'gabie',
  'gabro', 'gafat', 'gafez', 'gagat', 'gagic', 'gagiu', 'gaiac', 'gaial', 'gaibe', 'gaica',
  'gaică', 'gaidă', 'gaiză', 'gaiță', 'galet', 'galez', 'galeș', 'galic', 'galiu', 'galoș',
  'gamat', 'gamet', 'gangă', 'garat', 'garda', 'gardo', 'garez', 'garou', 'gater', 'gaura',
  'gauro', 'gauss', 'gauși', 'gavaj', 'gazat', 'gazel', 'gazeu', 'gazez', 'gazon', 'gazos',
  'gașca', 'gașco', 'geală', 'geamă', 'gebea', 'gecko', 'gedit', 'gelat', 'gelep', 'geliv',
  'gemat', 'gemea', 'gemem', 'gemen', 'gemet', 'gemui', 'gemut', 'gemăt', 'genat', 'genic',
  'genol', 'genom', 'genue', 'genți', 'geodă', 'geoid', 'gepid', 'gerah', 'gerar', 'gerat',
  'geret', 'gerez', 'gerid', 'geros', 'gerui', 'getic', 'ghebă', 'ghenă', 'ghete', 'gheto',
  'ghidă', 'ghint', 'ghinț', 'ghiob', 'ghioc', 'ghiol', 'ghioș', 'ghiuj', 'ghiul', 'ghizd',
  'giacă', 'gibon', 'gibos', 'gigea', 'ginit', 'gintă', 'ginși', 'girat', 'girez', 'girus',
  'glajă', 'gland', 'glanț', 'glavă', 'glebă', 'gleic', 'glenc', 'gleră', 'glial', 'glibc',
  'glifă', 'gliom', 'glonț', 'glosă', 'glotă', 'gmail', 'gnais', 'gnome', 'gnoză', 'gnuul',
  'goala', 'goale', 'goalo', 'goală', 'gobie', 'godac', 'goden', 'godeu', 'godie', 'godin',
  'gogit', 'gogon', 'golaș', 'golii', 'golit', 'golul', 'goluț', 'gomaj', 'gomos', 'gonaș',
  'gonio', 'gonit', 'gopac', 'gorun', 'gotcă', 'gotic', 'graba', 'grabe', 'grafă', 'grală',
  'grant', 'grapă', 'grasă', 'graur', 'gravă', 'great', 'grece', 'greci', 'greco', 'greez',
  'grejă', 'grena', 'grețe', 'greți', 'grier', 'griez', 'grifă', 'grija', 'grije', 'griji',
  'grijo', 'grimă', 'grind', 'grivă', 'grobă', 'gropi', 'gruia', 'gruie', 'gruii', 'gruio',
  'grund', 'grunz', 'grupă', 'grâie', 'grâna', 'grâne', 'grâno', 'grână', 'grâul', 'grăit',
  'guano', 'guard', 'guașă', 'gubav', 'gudur', 'guelf', 'guguț', 'guița', 'guițe', 'guiți',
  'guiță', 'gujon', 'gulag', 'gulaș', 'gulet', 'gulie', 'gumaj', 'gumat', 'gumez', 'gumos',
  'gurar', 'gureș', 'gurmă', 'gurnă', 'gurut', 'gurăi', 'guseu', 'gutos', 'gutui', 'guvid',
  'guzlă', 'gușat', 'gușii', 'gâcit', 'gâdil', 'gâfâi', 'gâgâi', 'gâjâi', 'gâlcă', 'gâlmă',
  'gâmba', 'gâmbe', 'gârlă', 'gâsca', 'gâsco', 'gâscă', 'gâtar', 'gâtos', 'gâște', 'găgăi',
  'găici', 'găman', 'gării', 'gărzi', 'găsca', 'găsco', 'găscă', 'gătej', 'gătez', 'gătit',
  'găvan', 'găzar', 'găști', 'haban', 'habar', 'hadal', 'hagiu', 'haham', 'haide', 'haiku',
  'haios', 'halaj', 'halal', 'halbă', 'halca', 'halco', 'halcă', 'haldă', 'halin', 'halit',
  'halon', 'halor', 'haltă', 'halău', 'hamei', 'hamit', 'hamiș', 'hampă', 'hamut', 'hanap',
  'hanat', 'hansă', 'hanță', 'hapcă', 'harac', 'harag', 'haram', 'harap', 'harem', 'hares',
  'harfă', 'haric', 'harpă', 'harta', 'harto', 'harșa', 'harță', 'hasca', 'hască', 'hatie',
  'hatâr', 'havai', 'havaj', 'havan', 'havat', 'havez', 'havră', 'havuz', 'hazna', 'haznă',
  'hașcă', 'hașeu', 'hașiș', 'hașmă', 'heder', 'helge', 'helgi', 'heliu', 'henri', 'hepar',
  'hermă', 'hersă', 'hertz', 'herul', 'hexan', 'hiadă', 'hidos', 'hidro', 'hidră', 'hienă',
  'hierb', 'hilar', 'himen', 'hindi', 'hioid', 'hiolă', 'hiper', 'hipic', 'hippy', 'hirtă',
  'hitit', 'hleab', 'hoață', 'hoban', 'hobby', 'hobot', 'hobâc', 'hogaș', 'hoher', 'hohot',
  'holdă', 'homar', 'hopăi', 'hordă', 'horeț', 'horit', 'horst', 'horăi', 'hoție', 'hoțit',
  'hramă', 'hrean', 'hreni', 'hrubă', 'huhur', 'huiet', 'huilă', 'huire', 'huită', 'huița',
  'huiță', 'hulit', 'hulpi', 'hulub', 'humic', 'humor', 'humos', 'humus', 'hunic', 'hural',
  'hurcă', 'hurez', 'hurie', 'huron', 'hurtă', 'hurui', 'husar', 'husca', 'huscă', 'husit',
  'husoș', 'husăș', 'huzur', 'huște', 'huști', 'huțan', 'huțul', 'huțuț', 'hâcâi', 'hâire',
  'hâită', 'hârcă', 'hârâi', 'hârău', 'hârță', 'hâtru', 'hâtră', 'hâzit', 'hâțâi', 'hăbuc',
  'hăire', 'hăisă', 'hăită', 'hălci', 'hămei', 'hărău', 'hărți', 'hătit', 'hăuit', 'hăzos',
  'hăști', 'hățaș', 'hățit', 'hățiș', 'iadeș', 'iarba', 'iarbo', 'iarna', 'iarno', 'iartă',
  'iască', 'iasmă', 'iatac', 'iaurt', 'iazma', 'iazmă', 'ibook', 'icnet', 'icnit', 'icter',
  'ictus', 'idală', 'ideat', 'ideea', 'ideez', 'ideii', 'idesk', 'idiom', 'idiot', 'iedei',
  'ieduț', 'iepei', 'iepii', 'ierhă', 'ierna', 'ierni', 'ierte', 'iertă', 'ierți', 'iesle',
  'iestă', 'iezer', 'iezit', 'iezme', 'ieșea', 'ieșii', 'ieșim', 'ieșit', 'ignar', 'ignat',
  'ignor', 'iilor', 'iiuri', 'ilaie', 'ilară', 'ileie', 'ileon', 'ileul', 'ileus', 'iliac',
  'ilion', 'iliră', 'ilăul', 'imacs', 'imago', 'imerg', 'imers', 'imnic', 'impas', 'impiu',
  'impun', 'impur', 'impus', 'imput', 'imund', 'imună', 'inapt', 'inbox', 'incas', 'incaș',
  'incit', 'incot', 'incub', 'indan', 'index', 'indic', 'indiu', 'indol', 'induc', 'indus',
  'inela', 'inemă', 'inept', 'inerm', 'inert', 'inetd', 'infim', 'infix', 'infra', 'infuz',
  'inhib', 'inima', 'inimi', 'inimo', 'inion', 'iniță', 'input', 'inter', 'intre', 'intri',
  'intru', 'intră', 'inuit', 'inule', 'inund', 'invar', 'invit', 'invoc', 'iobag', 'iodat',
  'iodic', 'iofca', 'ionar', 'ionat', 'ionic', 'ioniu', 'ipsos', 'irbis', 'ireal', 'irită',
  'irmos', 'irump', 'irumt', 'irupe', 'iscat', 'islam', 'islaz', 'isnaf', 'ispas', 'ispol',
  'istei', 'istor', 'istov', 'istui', 'iubeț', 'iudeo', 'iudeu', 'iugăr', 'iuiai', 'iuiam',
  'iuiau', 'iuind', 'iuire', 'iuiră', 'iuise', 'iuită', 'iuiși', 'iuiți', 'iureș', 'iurtă',
  'iuruș', 'iurăș', 'iuxtă', 'iușcă', 'iuțar', 'iuțit', 'ivesc', 'ivire', 'ivită', 'izbit',
  'izbuc', 'izdat', 'izlaz', 'izvod', 'ișlic', 'iștia', 'ițesc', 'ițire', 'ițită', 'jabie',
  'jabou', 'jalbă', 'jalea', 'jalei', 'jalet', 'jaleș', 'jalon', 'jambă', 'japca', 'japon',
  'japșă', 'jarca', 'jarcă', 'jardă', 'jaret', 'javră', 'jedit', 'jegos', 'jejun', 'jelea',
  'jelei', 'jeler', 'jelit', 'jenat', 'jenez', 'jerbă', 'jerfă', 'jerse', 'jeteu', 'jeton',
  'jiană', 'jidan', 'jidov', 'jiglă', 'jigou', 'jilip', 'jipan', 'jipat', 'jitar', 'jitie',
  'joace', 'joasă', 'jocot', 'jocuț', 'jofră', 'joian', 'joile', 'joker', 'joncă', 'jucai',
  'jucam', 'jucau', 'jucăm', 'judec', 'jugal', 'jugan', 'jugăr', 'juice', 'jujeu', 'jujău',
  'julep', 'julfă', 'julit', 'juncă', 'junel', 'junie', 'junit', 'juntă', 'jupan', 'jupit',
  'jupoi', 'jupon', 'jupui', 'jupân', 'justă', 'juvăț', 'juxtă', 'juzii', 'jăcaș', 'jărci',
  'kaliu', 'kanji', 'karma', 'karme', 'kavei', 'kazah', 'ketei', 'khmer', 'kibuț', 'koala',
  'kovar', 'kraft', 'kurdă', 'laban', 'labie', 'labil', 'labru', 'lacră', 'ladin', 'lagon',
  'lagăr', 'lahar', 'laiță', 'lamat', 'lambă', 'lamez', 'lampa', 'lampo', 'landă', 'lapis',
  'lapon', 'lapăd', 'lapți', 'larga', 'largi', 'largă', 'lasou', 'latex', 'latir', 'latre',
  'latri', 'latru', 'laude', 'lauzi', 'lavaj', 'laviu', 'lavră', 'layer', 'leafa', 'leagă',
  'leasă', 'lecit', 'lefei', 'lefii', 'legai', 'legam', 'legat', 'legau', 'legea', 'leghe',
  'legic', 'legii', 'legăm', 'legăn', 'leică', 'leită', 'leiță', 'lejer', 'lelea', 'lelei',
  'lelii', 'lenaj', 'lenea', 'lenei', 'lenii', 'lenos', 'lentă', 'leone', 'lepră', 'lepăd',
  'lepșe', 'lesne', 'letcă', 'leton', 'leuaș', 'leucă', 'levei', 'levit', 'lexem', 'lexic',
  'lexie', 'lezat', 'lezez', 'leșie', 'leșit', 'liant', 'liană', 'licit', 'licur', 'licăr',
  'liftă', 'ligav', 'ligii', 'limax', 'limba', 'limbi', 'limbo', 'limen', 'limes', 'limfă',
  'linon', 'linou', 'linsă', 'linți', 'liotă', 'lipan', 'lipie', 'lipit', 'lipom', 'lipsa',
  'lipse', 'lisat', 'lisez', 'litas', 'litic', 'litie', 'litiu', 'litou', 'litră', 'livan',
  'livid', 'livră', 'lizat', 'lizez', 'lizol', 'loază', 'lobar', 'lobat', 'lobby', 'lobdă',
  'lobez', 'lobul', 'local', 'locaș', 'locma', 'locul', 'lodbă', 'loden', 'loess', 'login',
  'logos', 'lojii', 'lonjă', 'loran', 'loris', 'lotcă', 'loton', 'lotru', 'lotră', 'lotus',
  'lovea', 'lovit', 'lozie', 'lspci', 'luare', 'luară', 'luase', 'luate', 'luată', 'luași',
  'luați', 'lucit', 'lucre', 'lucri', 'lucși', 'ludic', 'luetă', 'lufar', 'lugol', 'lujer',
  'lulea', 'lumea', 'lumei', 'lumen', 'lumeo', 'lumeț', 'lumii', 'luncă', 'lunea', 'lunec',
  'lunga', 'lungi', 'lungă', 'lunic', 'lunii', 'lupan', 'lupic', 'lupin', 'lupit', 'lupoi',
  'lupon', 'lupul', 'lupus', 'lurex', 'lutos', 'lutru', 'lutră', 'luxat', 'luxez', 'luxon',
  'luxos', 'luxul', 'luând', 'lușat', 'lușez', 'lânar', 'lânii', 'lânos', 'lăbos', 'lăcar',
  'lăcat', 'lăcaș', 'lădoi', 'lăieș', 'lăieț', 'lălâu', 'lălâă', 'lămpi', 'lămâi', 'lănci',
  'lăpăi', 'lăsai', 'lăsam', 'lăsat', 'lăsau', 'lăsăm', 'lătoc', 'lătra', 'lătră', 'lăuda',
  'lăudă', 'lăută', 'lăuză', 'lăzii', 'lățit', 'lățiș', 'lățos', 'macac', 'macat', 'macaz',
  'macin', 'maclă', 'macru', 'macră', 'madam', 'madea', 'mafie', 'magmă', 'magno', 'magot',
  'mahar', 'mahon', 'mahăr', 'maial', 'maian', 'maiei', 'maieu', 'maiou', 'maișă', 'malac',
  'malad', 'malar', 'malic', 'malin', 'mamar', 'mambo', 'mamii', 'mamoș', 'mamut', 'manat',
  'manco', 'mancă', 'manea', 'manej', 'mantă', 'manșă', 'maori', 'mapez', 'maraz', 'marca',
  'marco', 'marda', 'maref', 'marei', 'marfa', 'marfo', 'margă', 'marii', 'marin', 'marjă',
  'marnă', 'maron', 'maroă', 'marșă', 'masat', 'masca', 'masco', 'maser', 'masez', 'masic',
  'maslu', 'maslă', 'mason', 'masor', 'matca', 'matco', 'matez', 'matol', 'mator', 'matuf',
  'mauși', 'maxit', 'mazil', 'mazur', 'mașez', 'mecet', 'mecăi', 'media', 'medii', 'medio',
  'mefia', 'mehăi', 'mejdă', 'meleu', 'melez', 'melii', 'meliț', 'melon', 'melos', 'melul',
  'menit', 'meniu', 'menou', 'mentă', 'merar', 'merii', 'mersi', 'mersă', 'metan', 'metec',
  'meteo', 'metil', 'metis', 'metoc', 'metoh', 'metol', 'metra', 'metro', 'metru', 'mezat',
  'mezel', 'mezin', 'mezon', 'mește', 'miala', 'mială', 'miaua', 'miaun', 'miaut', 'miază',
  'micit', 'micro', 'micuț', 'midie', 'miele', 'mieru', 'mieză', 'migmă', 'miile', 'miime',
  'mijii', 'mijit', 'mileu', 'milog', 'mimat', 'mimez', 'mimic', 'minaj', 'minei', 'miner',
  'minez', 'mingi', 'miniu', 'mintă', 'mință', 'miopi', 'miopă', 'mioză', 'miraj', 'mirat',
  'miraz', 'mirez', 'mirii', 'misie', 'misir', 'misit', 'mitic', 'mitoc', 'mitră', 'miuon',
  'miuță', 'mixaj', 'mixat', 'mixer', 'mixez', 'mixta', 'mixte', 'mixtă', 'mizat', 'mizer',
  'mizez', 'mișel', 'miște', 'mișto', 'mișui', 'mișun', 'mițos', 'mlaca', 'mlacă', 'mlada',
  'mladă', 'mlajă', 'mlăci', 'mlăzi', 'moacă', 'moaie', 'moare', 'moază', 'moașă', 'moață',
  'mocan', 'modal', 'modem', 'modic', 'modru', 'modul', 'modus', 'mogul', 'mohor', 'moile',
  'moimă', 'moină', 'mojar', 'mojic', 'molal', 'molan', 'molar', 'molat', 'moldă', 'molei',
  'molet', 'molez', 'molid', 'moloh', 'molon', 'molos', 'moloz', 'momâi', 'monac', 'monah',
  'monem', 'monom', 'monoă', 'montă', 'morav', 'morgă', 'moria', 'morii', 'moroi', 'moron',
  'morsă', 'mortă', 'morun', 'moruă', 'morvă', 'moscu', 'mosor', 'motan', 'motel', 'motet',
  'motoc', 'moșic', 'moșit', 'moști', 'moțat', 'moțez', 'moțit', 'mreje', 'mrejă', 'mucar',
  'mucea', 'muced', 'muche', 'muchi', 'mucos', 'mucus', 'mudir', 'muflă', 'mugit', 'muhur',
  'muiai', 'muiaj', 'muiam', 'muiat', 'muiau', 'muică', 'muiem', 'muind', 'mujic', 'mulaj',
  'mulat', 'mulez', 'mulsă', 'multi', 'multă', 'mural', 'murar', 'murea', 'murez', 'murid',
  'murii', 'murim', 'murin', 'murit', 'muriș', 'mursă', 'musai', 'musca', 'musco', 'musez',
  'musiu', 'muson', 'mutat', 'mutic', 'mutit', 'muton', 'muzic', 'mușat', 'muște', 'muție',
  'muțit', 'mysql', 'mâcâi', 'mâglă', 'mâini', 'mâlit', 'mâlos', 'mânai', 'mânam', 'mânat',
  'mânau', 'mânaș', 'mâncă', 'mânea', 'mânec', 'mânem', 'mânie', 'mânză', 'mânăm', 'mârli',
  'mâtcă', 'mâzga', 'mâzgi', 'mâzgo', 'mâzgă', 'mâșâi', 'mâțan', 'mâțit', 'mâțoi', 'mâțuc',
  'măcel', 'măceș', 'măcăi', 'măici', 'măiug', 'măiuț', 'măjar', 'măjer', 'mălai', 'mălin',
  'măluț', 'mămic', 'mămos', 'mănat', 'mănau', 'mănos', 'mărar', 'mărat', 'măraz', 'mărci',
  'mărfi', 'mărie', 'mărit', 'măroi', 'mărul', 'măruț', 'măsar', 'măsei', 'măsoi', 'măsor',
  'mătci', 'mătur', 'măști', 'mățar', 'nabab', 'nacru', 'nadir', 'naftă', 'nagâț', 'nahtă',
  'naiba', 'naica', 'naici', 'naică', 'naira', 'naist', 'nakfa', 'nalbă', 'naltă', 'nalțe',
  'nalți', 'nalță', 'namaz', 'nandu', 'napoi', 'narat', 'narez', 'nască', 'nasol', 'nativ',
  'natră', 'natur', 'naval', 'navlu', 'nazar', 'nazir', 'nazâr', 'nașpa', 'nașpă', 'naști',
  'nație', 'neaga', 'neagă', 'nealt', 'neamț', 'neant', 'neaoș', 'neaua', 'neauă', 'necum',
  'neder', 'nefac', 'nefer', 'neflă', 'negat', 'negel', 'negos', 'negoț', 'negre', 'negri',
  'negră', 'negus', 'neica', 'neicu', 'neică', 'neios', 'nelas', 'nemet', 'nemeș', 'nemți',
  'nenea', 'nenei', 'nenic', 'neper', 'nerod', 'nesaț', 'netez', 'netot', 'neumă', 'neuro',
  'nevod', 'nezai', 'nezam', 'nezau', 'nezâi', 'nezâm', 'nezât', 'nicio', 'nicol', 'nielă',
  'nimfă', 'ninsă', 'niper', 'niplu', 'nipon', 'nitui', 'nival', 'nixis', 'nizam', 'nițel',
  'noadă', 'nodal', 'nodos', 'nodul', 'noduț', 'noemă', 'noian', 'noile', 'noime', 'noimă',
  'noiță', 'nomad', 'nomol', 'nonet', 'noneu', 'nopal', 'nopez', 'nopți', 'nordă', 'norea',
  'norei', 'noriu', 'norod', 'noros', 'noruț', 'nostă', 'notar', 'notat', 'notes', 'notez',
  'nouar', 'nouță', 'novac', 'novat', 'novez', 'ntorc', 'nubil', 'nubuc', 'nucar', 'nucet',
  'nucuț', 'numen', 'numit', 'nunta', 'nunto', 'nunți', 'nurcă', 'nursă', 'nvață', 'nânaș',
  'năboi', 'năbuc', 'năbuș', 'năcaz', 'năduf', 'năduh', 'năhut', 'năier', 'năjit', 'nălța',
  'nălță', 'nămeț', 'nămit', 'nănaș', 'nărod', 'nărui', 'născu', 'năsip', 'năsoi', 'năsos',
  'năsuc', 'năsut', 'năsuț', 'năucă', 'năvod', 'năzui', 'nășel', 'nășic', 'nășie', 'nășit',
  'oacăr', 'oardă', 'oarze', 'oaspe', 'obada', 'obadă', 'obelă', 'obezi', 'obeză', 'obidă',
  'obleț', 'oblic', 'oblig', 'obora', 'obori', 'oborî', 'obraț', 'obroc', 'obtuz', 'obște',
  'obști', 'obție', 'obțin', 'obțiu', 'ocale', 'ocaua', 'ocauo', 'ocauă', 'oceli', 'ocelu',
  'ocheț', 'ochit', 'ocina', 'ocine', 'ocini', 'ocină', 'ocnaș', 'ocolă', 'octal', 'octan',
  'octet', 'ocult', 'ocăie', 'ocăit', 'ocăra', 'ocărî', 'odaia', 'odaie', 'odaio', 'odeon',
  'odgon', 'odină', 'odora', 'odăii', 'ofere', 'oferă', 'ofset', 'oftat', 'oftez', 'oftic',
  'ofusc', 'ogeac', 'ogivă', 'ogoie', 'ogoit', 'ogora', 'ogorî', 'ohabă', 'ohmic', 'oiesc',
  'oilor', 'oindu', 'oiște', 'olacă', 'olană', 'oleat', 'oleic', 'oleul', 'oleum', 'olivă',
  'oliță', 'olmaz', 'oloit', 'oltar', 'omega', 'omeți', 'omiat', 'omise', 'omisă', 'omora',
  'omori', 'omorî', 'omule', 'omătu', 'onori', 'ontic', 'oocit', 'oofag', 'oogon', 'oolit',
  'opacă', 'opaiț', 'opiat', 'opium', 'opreg', 'oprim', 'opsas', 'optar', 'optat', 'optez',
  'optic', 'opust', 'opusă', 'orală', 'oranj', 'orant', 'oranz', 'orară', 'orașă', 'orbec',
  'orbeț', 'orbie', 'orbit', 'orcan', 'orcic', 'ordie', 'ordon', 'oreav', 'orfic', 'orgie',
  'orier', 'orjad', 'orlon', 'ornat', 'ornez', 'ornic', 'ortac', 'ortic', 'orzar', 'orzul',
  'orând', 'osana', 'oseta', 'osete', 'osetă', 'oseți', 'osman', 'osmiu', 'osmol', 'osram',
  'ostic', 'ostie', 'osuar', 'otavă', 'otcup', 'otfel', 'otgon', 'otinc', 'otită', 'otova',
  'ouare', 'ouară', 'ouase', 'ouleț', 'oului', 'outor', 'ouând', 'ouăle', 'oușor', 'ovală',
  'ovată', 'oveze', 'ovină', 'ovoid', 'ovrei', 'ovreu', 'ovăzu', 'oxiur', 'ozenă', 'oșean',
  'oștii', 'oțelă', 'oțera', 'oțerî', 'oțios', 'oțăra', 'oțărî', 'pacea', 'paceo', 'padoc',
  'pafta', 'pager', 'pagur', 'paiet', 'paile', 'paing', 'paiol', 'paion', 'paiul', 'palan',
  'palas', 'palcă', 'palee', 'palie', 'paloș', 'palpă', 'palux', 'pamat', 'pamez', 'panaș',
  'panda', 'panel', 'paner', 'panez', 'panic', 'papal', 'papat', 'papei', 'papii', 'papir',
  'papus', 'parat', 'parei', 'parez', 'parfe', 'parip', 'pariu', 'paroi', 'parsa', 'parsă',
  'partă', 'pasat', 'pasca', 'pască', 'pasez', 'patei', 'pater', 'pateu', 'patio', 'patos',
  'patra', 'patul', 'paucă', 'pavaj', 'pavat', 'pavea', 'pavez', 'pavor', 'pazie', 'pașcă',
  'pașol', 'paști', 'pașuș', 'peană', 'pecar', 'pecie', 'peciu', 'pedel', 'pefug', 'pegas',
  'pegră', 'pejmă', 'pelaj', 'pelin', 'pelit', 'pelur', 'pembe', 'penaj', 'penal', 'penat',
  'penei', 'penet', 'penez', 'penin', 'penis', 'pensi', 'pensă', 'pepit', 'peplu', 'pepsi',
  'perei', 'peren', 'pereu', 'perie', 'perii', 'periș', 'perjă', 'peruș', 'pesar', 'pesos',
  'pestă', 'petas', 'petec', 'petei', 'petit', 'peșin', 'pești', 'pețit', 'pfund', 'phpbb',
  'piano', 'piața', 'piațo', 'picaj', 'picol', 'picon', 'picot', 'picou', 'picup', 'picuș',
  'picuț', 'pieii', 'pielm', 'pierd', 'piere', 'pierz', 'pieta', 'piețe', 'pifan', 'pilaf',
  'pilit', 'pilor', 'pilos', 'pilug', 'pinot', 'pință', 'piotă', 'pipat', 'pipez', 'pipit',
  'pireu', 'pirex', 'piric', 'pirol', 'pirop', 'pirui', 'pisar', 'pisat', 'piser', 'pisez',
  'pisic', 'pitac', 'pitar', 'pitit', 'pitiș', 'pitoi', 'piton', 'piuar', 'piuat', 'piuez',
  'piuit', 'piure', 'pivot', 'pixel', 'pizmă', 'pizză', 'pișai', 'pișam', 'pișat', 'pișau',
  'pișcă', 'piște', 'pișăm', 'placa', 'place', 'placi', 'placo', 'plaga', 'plago', 'plagă',
  'plană', 'plata', 'plato', 'plaur', 'plavă', 'plean', 'pleci', 'plecă', 'plete', 'pleve',
  'pleșă', 'pliaj', 'pliat', 'plică', 'pliez', 'plimb', 'plior', 'plită', 'ploii', 'plouă',
  'plâng', 'plăci', 'plăcu', 'plăgi', 'plăși', 'plăți', 'poamă', 'poară', 'poată', 'pocal',
  'pocie', 'pocit', 'podan', 'podar', 'podeț', 'podit', 'poduț', 'poemă', 'poetă', 'pofil',
  'pogan', 'pogon', 'pogor', 'pohod', 'pohoi', 'pohoț', 'poker', 'polar', 'polcă', 'polip',
  'polis', 'poliș', 'polje', 'polog', 'polon', 'pomet', 'ponce', 'ponit', 'ponor', 'ponos',
  'pontă', 'popas', 'popaz', 'popei', 'popic', 'popie', 'popii', 'popit', 'popol', 'popou',
  'popul', 'porno', 'poros', 'porto', 'portă', 'porți', 'posed', 'postă', 'potcă', 'potir',
  'potol', 'potou', 'povod', 'povoi', 'pozar', 'pozat', 'pozez', 'poznă', 'pppoe', 'prada',
  'prade', 'praji', 'prană', 'prare', 'praxă', 'prazi', 'prazu', 'prașă', 'predă', 'prefă',
  'preia', 'prian', 'prici', 'prier', 'priim', 'priit', 'prima', 'primu', 'primă', 'prind',
  'print', 'prior', 'pripa', 'pripe', 'produ', 'profă', 'promo', 'proră', 'prour', 'provă',
  'prudă', 'pruja', 'pruji', 'prujă', 'prunc', 'prăda', 'prăde', 'prădă', 'prăzi', 'psalm',
  'psalt', 'psoas', 'ptoză', 'puber', 'pubis', 'puchi', 'pudel', 'pudic', 'pufos', 'pufăr',
  'puhav', 'puiat', 'puică', 'puiet', 'puind', 'puios', 'puire', 'puită', 'puiuț', 'pulie',
  'pulpă', 'pumei', 'pumnă', 'punci', 'punea', 'punga', 'pungi', 'pungo', 'punic', 'punți',
  'pupat', 'pupic', 'pupil', 'purec', 'puric', 'purim', 'purjă', 'puroi', 'purtă', 'puseu',
  'pustă', 'putem', 'putui', 'putut', 'puvoi', 'pușca', 'pușco', 'puște', 'puști', 'puțar',
  'puțea', 'puții', 'puțim', 'puțit', 'puțoi', 'pâcâi', 'pâcăi', 'pândă', 'pârgă', 'pârât',
  'pârâș', 'pârăi', 'pâslă', 'pâșin', 'păcii', 'păfug', 'păier', 'păios', 'păiuș', 'păiuț',
  'pălit', 'pălmi', 'păpai', 'păpam', 'păpat', 'păpau', 'păpuc', 'păpăm', 'păraș', 'părem',
  'păros', 'părui', 'părul', 'părut', 'păsai', 'păsam', 'păsat', 'păsau', 'păscu', 'păsăm',
  'pătez', 'pătuc', 'pătul', 'pătuț', 'păună', 'păzit', 'pășit', 'păști', 'pățit', 'qmail',
  'qsort', 'quarc', 'quipu', 'rabat', 'rabde', 'rabdă', 'rabic', 'rabie', 'rabin', 'rabiț',
  'rablă', 'rabzi', 'racem', 'racii', 'raclă', 'racul', 'radar', 'radem', 'radiu', 'radom',
  'radon', 'radou', 'rafie', 'ragea', 'ragil', 'rahat', 'rahis', 'raibă', 'raită', 'rajah',
  'ralid', 'ramat', 'ramcă', 'ramer', 'ramez', 'ramie', 'ramos', 'ranch', 'randă', 'ranga',
  'rango', 'rangă', 'rapel', 'rapăn', 'rasat', 'rasol', 'rataj', 'rateu', 'ratez', 'rateș',
  'ratoș', 'ravac', 'razie', 'raznă', 'razăm', 'rașca', 'rașcă', 'rașel', 'rașpă', 'rațcă',
  'readu', 'reală', 'reară', 'reaua', 'rebab', 'rebec', 'rebus', 'rebut', 'recea', 'recif',
  'recii', 'recit', 'recte', 'recto', 'recul', 'recuz', 'redam', 'redan', 'redat', 'redie',
  'rediu', 'redox', 'redus', 'refac', 'refec', 'refer', 'refuz', 'regat', 'regea', 'regie',
  'regii', 'regim', 'regit', 'reiat', 'reidă', 'rejet', 'relat', 'relaș', 'relei', 'relev',
  'relon', 'remis', 'remit', 'renal', 'renan', 'renci', 'renet', 'renie', 'reniu', 'reniș',
  'rentă', 'renul', 'repar', 'reped', 'repet', 'repez', 'resac', 'reset', 'retez', 'retor',
  'retro', 'retur', 'retuș', 'reumă', 'reuns', 'revat', 'rever', 'reviu', 'revoc', 'revăz',
  'rezec', 'rezem', 'rezil', 'rezol', 'rezon', 'rezum', 'reșcă', 'reșou', 'reție', 'rețiu',
  'ricin', 'ricșă', 'ridat', 'ridez', 'ridic', 'riflu', 'rigii', 'rigăi', 'rimat', 'rimel',
  'rimez', 'ripat', 'ripez', 'risca', 'riscă', 'ritor', 'ritos', 'rizat', 'rizez', 'rizic',
  'rizil', 'rizom', 'rișca', 'rișcă', 'riște', 'riști', 'roabă', 'roadă', 'roage', 'roagă',
  'roase', 'roasă', 'roata', 'roato', 'roază', 'robie', 'robit', 'roche', 'rochi', 'rodaj',
  'rodan', 'rodat', 'rodeo', 'rodez', 'rodin', 'rodit', 'rodiu', 'rodor', 'rodos', 'rogoz',
  'roibă', 'roire', 'roită', 'rolan', 'rolat', 'român', 'rondo', 'rondă', 'ropot', 'rosei',
  'rotar', 'rotat', 'rotaș', 'rotea', 'rotez', 'rotit', 'rotor', 'roura', 'roziu', 'roșaj',
  'roșit', 'roșiu', 'roții', 'rsync', 'rubil', 'rubin', 'rublă', 'rudar', 'rudit', 'rufar',
  'rufos', 'rugai', 'rugam', 'rugat', 'rugau', 'ruget', 'rugit', 'rugos', 'rugăm', 'ruină',
  'rujan', 'rujar', 'rujet', 'rujez', 'rulaj', 'rulat', 'rulez', 'ruliu', 'rulou', 'rumbă',
  'rumeg', 'rumen', 'rumpe', 'rumpi', 'rumpt', 'rumpă', 'rumse', 'rumân', 'runic', 'rupea',
  'rupie', 'rusav', 'ruscă', 'rusit', 'rutat', 'rutea', 'ruter', 'rutez', 'rutil', 'râbar',
  'râgâi', 'râiat', 'râile', 'râios', 'râlei', 'râmat', 'râmau', 'râncă', 'rânit', 'rânză',
  'râpat', 'râpei', 'râpii', 'râpos', 'râsem', 'râset', 'râtan', 'râura', 'râvnă', 'râznă',
  'răbdă', 'răboj', 'răbuș', 'răcan', 'răcar', 'răcit', 'rădea', 'rădic', 'rădiu', 'răgea',
  'răget', 'răgii', 'răgit', 'răgoz', 'răgut', 'răire', 'rămân', 'răngi', 'rănii', 'rănit',
  'răpit', 'răpun', 'răpus', 'rărit', 'răriș', 'răsad', 'răsar', 'răsei', 'răsuc', 'rătez',
  'răvar', 'răvaș', 'răzeș', 'răzor', 'răzuș', 'rășci', 'rățoi', 'sabat', 'sabia', 'sabin',
  'sabio', 'sabir', 'sable', 'sabot', 'sabur', 'sacos', 'sacou', 'sacru', 'sacră', 'sacul',
  'sacâz', 'sadea', 'sadic', 'safen', 'safeu', 'safic', 'safir', 'sagnă', 'sagum', 'sahan',
  'salbă', 'salep', 'saleu', 'salic', 'salin', 'salon', 'salop', 'salsa', 'salte', 'saltă',
  'salvă', 'salți', 'salță', 'samar', 'sambă', 'samcă', 'sameș', 'samur', 'sanct', 'sanda',
  'sania', 'sapan', 'sapid', 'sarai', 'sarea', 'saric', 'saros', 'satan', 'satir', 'satul',
  'satur', 'satâr', 'saulă', 'saună', 'saxon', 'sașeu', 'sașiu', 'scade', 'scadă', 'scafă',
  'scald', 'scamă', 'scape', 'scapi', 'scapă', 'scarp', 'scazi', 'schif', 'schip', 'schit',
  'sclai', 'scoci', 'scoli', 'scont', 'scopt', 'scose', 'scotă', 'scoți', 'screm', 'scria',
  'scrib', 'scrii', 'scrin', 'scris', 'scriu', 'scrob', 'scrot', 'scufă', 'scuip', 'sculă',
  'scurg', 'scurm', 'scurs', 'scuză', 'scârț', 'scăpă', 'scăzu', 'seaca', 'seaco', 'seacă',
  'seama', 'seamă', 'sebum', 'secai', 'secam', 'secau', 'secer', 'sectă', 'secui', 'secăm',
  'sedez', 'sediu', 'seduc', 'sedus', 'seigă', 'seimă', 'seișă', 'sejur', 'selbă', 'selvă',
  'semem', 'semen', 'semic', 'semii', 'semit', 'semăn', 'senar', 'senat', 'senil', 'separ',
  'sepie', 'seraf', 'serai', 'seral', 'seric', 'seros', 'servă', 'sesam', 'sesie', 'sesil',
  'setat', 'setcă', 'setea', 'seteo', 'seter', 'setez', 'setos', 'sevai', 'sevas', 'sextă',
  'sfada', 'sfado', 'sfadă', 'sfanț', 'sfară', 'sfiii', 'sfiim', 'sfiit', 'sfinx', 'sfios',
  'sfită', 'sfârc', 'sfăzi', 'sială', 'sicar', 'sidef', 'sieși', 'siglă', 'sigma', 'sihlă',
  'silan', 'silcă', 'silen', 'silex', 'silfă', 'silit', 'silon', 'siloz', 'silur', 'silvă',
  'simit', 'simte', 'simtă', 'simun', 'simți', 'simță', 'sinea', 'sinet', 'sineț', 'sinie',
  'sinod', 'sinua', 'sinus', 'sipet', 'sirec', 'sirep', 'sisal', 'sitar', 'sixtă', 'slabă',
  'slană', 'sleit', 'slops', 'slovă', 'sluga', 'slugi', 'slugo', 'slugă', 'sluis', 'slută',
  'smalț', 'smbfs', 'smeci', 'smeșa', 'smidă', 'smulg', 'smuls', 'smârc', 'smârd', 'snobă',
  'snort', 'soață', 'sobar', 'sobol', 'sobor', 'sobru', 'sobră', 'socio', 'socot', 'sodar',
  'sodat', 'sodei', 'sodic', 'sodiu', 'sodom', 'sofra', 'soiei', 'soios', 'soire', 'soiul',
  'solbă', 'soldă', 'solie', 'solve', 'solvă', 'somat', 'somei', 'somez', 'somon', 'sonar',
  'sonez', 'sonic', 'sorab', 'sorei', 'soroc', 'sosie', 'sosit', 'sosma', 'sotez', 'sovon',
  'soție', 'spadă', 'spala', 'spale', 'spală', 'sparg', 'spart', 'spasm', 'spată', 'spelb',
  'spele', 'speli', 'spese', 'spete', 'speză', 'speță', 'spici', 'spină', 'spiră', 'splai',
  'splau', 'spoit', 'spuie', 'spurc', 'spusă', 'spută', 'spuză', 'spânz', 'spârc', 'spălă',
  'stadă', 'stală', 'stană', 'start', 'stată', 'stavă', 'stază', 'stați', 'stean', 'steie',
  'steli', 'stelă', 'stepă', 'stern', 'sterp', 'stete', 'sting', 'stoic', 'stolă', 'stopă',
  'storc', 'stors', 'strai', 'stras', 'strei', 'stric', 'strie', 'strig', 'striu', 'stroh',
  'stroi', 'strup', 'struț', 'stupă', 'sturz', 'stând', 'stâni', 'stârc', 'stârv', 'stătu',
  'sucit', 'sucks', 'sudaj', 'sudat', 'sudez', 'sudic', 'sudit', 'sudor', 'sudui', 'sufit',
  'sufix', 'suflu', 'sufoc', 'sufăr', 'sugar', 'sugel', 'suguș', 'suhat', 'suidă', 'suind',
  'suină', 'suire', 'suită', 'sujet', 'sulac', 'sultă', 'sumac', 'suman', 'sumat', 'sumec',
  'sumes', 'sumet', 'sumez', 'sumuț', 'supat', 'super', 'supeu', 'supez', 'supin', 'supra',
  'supse', 'suptă', 'supun', 'supus', 'supăr', 'sural', 'surdă', 'suret', 'suriu', 'surlă',
  'surou', 'surpa', 'surpe', 'surpă', 'surâd', 'surâz', 'susan', 'susur', 'sutar', 'sutaș',
  'sutea', 'suvac', 'svada', 'svadă', 'svelt', 'svezi', 'sysfs', 'sâneț', 'sârbă', 'sârmă',
  'sâsâi', 'săbii', 'săcoi', 'săcuț', 'sădit', 'sălaș', 'sălii', 'săltă', 'sănii', 'săpai',
  'săpam', 'săpat', 'săpau', 'săpie', 'săpăm', 'sărad', 'sărar', 'sărat', 'sărea', 'sărez',
  'sării', 'sărim', 'sărit', 'săros', 'săsit', 'sătit', 'sătuc', 'sătui', 'sătul', 'sătuț',
  'tabac', 'taban', 'tabar', 'tabes', 'tabie', 'tabla', 'tabun', 'tabăr', 'tacit', 'tacla',
  'tacâm', 'tafta', 'taftă', 'tagmă', 'tagăi', 'tahân', 'taica', 'taică', 'taier', 'taiga',
  'taior', 'talaj', 'talan', 'talar', 'talaz', 'talaș', 'taler', 'talim', 'taliu', 'talon',
  'talpa', 'talpo', 'talpă', 'talus', 'taluz', 'taman', 'tamar', 'tamâș', 'tanaj', 'tanat',
  'tanea', 'tanga', 'tango', 'tangă', 'tanic', 'tanin', 'tanti', 'tanăt', 'taolă', 'tapaj',
  'tapat', 'tapez', 'tapir', 'tarac', 'taraf', 'taraj', 'tarar', 'tarat', 'taraș', 'tarea',
  'tarei', 'tareo', 'targa', 'targo', 'targă', 'tarii', 'tarla', 'taroc', 'tarod', 'tasat',
  'taseu', 'tasez', 'tasma', 'tason', 'tastă', 'tatai', 'tatei', 'tatii', 'tatăl', 'taulă',
  'taxat', 'taxez', 'taxid', 'taxim', 'tașcă', 'tații', 'teaca', 'teama', 'teapa', 'teapă',
  'teară', 'teasc', 'tecii', 'tehno', 'tehui', 'teică', 'teier', 'teină', 'teios', 'teism',
  'teist', 'telal', 'telex', 'telur', 'temea', 'temei', 'temem', 'temii', 'tempo', 'temui',
  'tendă', 'tenie', 'tenor', 'tentă', 'tepei', 'teras', 'teraz', 'terfe', 'terme', 'ternă',
  'terra', 'terță', 'tesac', 'teslă', 'teucă', 'teugă', 'teșit', 'tiară', 'tibet', 'tibia',
  'tibii', 'tical', 'ticni', 'ticnă', 'tifan', 'tific', 'tiflă', 'tifon', 'tifos', 'tigvă',
  'tildă', 'timar', 'timie', 'timin', 'timol', 'timus', 'tindă', 'tinos', 'tinov', 'tinse',
  'tinzi', 'tinză', 'tipaj', 'tipie', 'tiraj', 'titan', 'titru', 'tiuit', 'tivgă', 'tivit',
  'tizic', 'tmeză', 'toacă', 'toană', 'toast', 'toasă', 'toate', 'toată', 'tobaș', 'tocat',
  'tocit', 'tofus', 'tolbă', 'tonaj', 'tonal', 'tondo', 'tonic', 'tonou', 'tonus', 'topaz',
  'topic', 'topuz', 'torci', 'torid', 'torit', 'toriu', 'torni', 'toron', 'torsă', 'tortă',
  'torși', 'total', 'totem', 'totul', 'toval', 'toxic', 'toții', 'traca', 'tract', 'tracă',
  'tradu', 'trafă', 'tragi', 'tragă', 'tramă', 'trapă', 'trasă', 'trată', 'traul', 'trebi',
  'treia', 'treji', 'tremă', 'trend', 'trenă', 'tresă', 'treze', 'triac', 'trial', 'triat',
  'trico', 'trier', 'triez', 'triod', 'trior', 'tronc', 'trosc', 'trota', 'trucă', 'trust',
  'trusă', 'trând', 'trăit', 'tubaj', 'tubat', 'tuber', 'tubez', 'tucan', 'tufan', 'tufar',
  'tufit', 'tufiș', 'tufos', 'tuiei', 'tuieș', 'tuile', 'tuior', 'tuiul', 'tulei', 'tuleu',
  'tulit', 'tuliu', 'tumbă', 'tumid', 'tumul', 'tunar', 'tundă', 'tuner', 'tunet', 'tunse',
  'tunzi', 'tunză', 'tupeu', 'turan', 'turau', 'turbă', 'turca', 'turce', 'turci', 'turco',
  'turcă', 'turnă', 'turtă', 'turui', 'tusea', 'tuset', 'tutor', 'tutun', 'tușeu', 'tușez',
  'tușit', 'tuție', 'tâmpă', 'tânga', 'tângi', 'tângă', 'tântă', 'târfă', 'târlă', 'târnă',
  'târsă', 'târâș', 'tâțoi', 'tăcem', 'tăcui', 'tăgii', 'tăiai', 'tăiam', 'tăiat', 'tăiau',
  'tăiem', 'tăier', 'tăind', 'tăios', 'tălpi', 'tămâi', 'tărgi', 'tătar', 'tătuc', 'tătuț',
  'tăuit', 'tăune', 'tăvii', 'ucide', 'ucidă', 'ucigă', 'ucise', 'ucizi', 'uciză', 'uclei',
  'udare', 'udată', 'uguia', 'uguie', 'uguit', 'uiați', 'uiesc', 'uirăm', 'uisem', 'uitit',
  'uituc', 'ujuie', 'ulcea', 'ulcer', 'ulcus', 'ulema', 'ultra', 'ulubă', 'uluca', 'uluci',
  'uluco', 'ulucă', 'uluit', 'umana', 'umane', 'umani', 'umană', 'umblu', 'umedă', 'umere',
  'umeri', 'umflu', 'umilă', 'umpli', 'umplu', 'umăru', 'uncie', 'undat', 'undef', 'undez',
  'undit', 'uneia', 'unele', 'unesc', 'ungar', 'ungur', 'uniat', 'uniax', 'unime', 'unire',
  'unită', 'unora', 'untar', 'untos', 'unuia', 'unule', 'unșpe', 'urale', 'urală', 'urare',
  'urată', 'urbea', 'urbei', 'urbii', 'urcat', 'urcuș', 'urdar', 'urdin', 'urduc', 'urgie',
  'urile', 'urină', 'urlat', 'urlet', 'urloi', 'urlup', 'urmat', 'urmaș', 'urmez', 'urnit',
  'ursar', 'ursin', 'ursit', 'ursoi', 'urson', 'uruit', 'urzic', 'urzit', 'urâre', 'urâră',
  'urâse', 'urâtă', 'urâși', 'urăsc', 'uscat', 'ustaș', 'usuce', 'usuci', 'usucă', 'utilă',
  'uviol', 'uvraj', 'uvulă', 'uzare', 'uzată', 'uzbec', 'uzual', 'uzurp', 'ușier', 'ușile',
  'ușiță', 'ușuță', 'vacat', 'vadea', 'vados', 'vadra', 'vadră', 'vagil', 'vagin', 'vaier',
  'vaiet', 'vaită', 'valah', 'valea', 'valeo', 'valex', 'valma', 'valmă', 'valon', 'valvă',
  'vamal', 'vameș', 'vampă', 'varec', 'varga', 'varsă', 'varus', 'varvă', 'varza', 'varzo',
  'vasal', 'vasel', 'vastă', 'vatir', 'vatos', 'vatra', 'vatro', 'vatăm', 'vazon', 'veaca',
  'veacă', 'veceu', 'veche', 'vecii', 'vedda', 'vedem', 'vedic', 'vedre', 'veghi', 'velar',
  'velic', 'velin', 'velit', 'velur', 'venal', 'venea', 'venet', 'venie', 'venii', 'venim',
  'venos', 'verei', 'vergi', 'vergă', 'veric', 'verif', 'verii', 'veros', 'verso', 'versă',
  'verze', 'verzi', 'verși', 'vetre', 'vexat', 'vexez', 'vexil', 'veșcă', 'vești', 'viată',
  'viața', 'viațo', 'vicar', 'viciu', 'vidaj', 'vidat', 'video', 'videz', 'vidmă', 'vidră',
  'vielă', 'viere', 'viers', 'vieți', 'vigie', 'vigil', 'vilos', 'vinar', 'vinaț', 'vinci',
  'vinei', 'vinii', 'vinil', 'vinuț', 'vinzi', 'vioii', 'violă', 'vipie', 'viplă', 'viraj',
  'viral', 'viran', 'virat', 'virez', 'virid', 'viril', 'visat', 'visez', 'vitae', 'vivat',
  'vizat', 'vizez', 'vizir', 'vizon', 'vizor', 'vițea', 'vițiu', 'vițos', 'vlaga', 'vlahă',
  'vocal', 'vocea', 'voceo', 'vocii', 'vodcă', 'voder', 'vogăi', 'voile', 'voire', 'voită',
  'volar', 'volet', 'voloc', 'volog', 'voltă', 'volve', 'vomat', 'vomer', 'vomez', 'vomic',
  'votat', 'votcă', 'votez', 'votiv', 'votru', 'votum', 'vraci', 'vrană', 'vrați', 'vreai',
  'vream', 'vreau', 'vreie', 'vremi', 'vrere', 'vreun', 'vreți', 'vrilă', 'vroit', 'vrună',
  'vrură', 'vruse', 'vrută', 'vruși', 'vrând', 'vuiet', 'vuind', 'vuire', 'vuită', 'vulpi',
  'vulvă', 'vurtă', 'vutcă', 'vuvar', 'vâjâi', 'vâlfă', 'vâlvă', 'vânat', 'vându', 'vândă',
  'vânez', 'vânos', 'vânză', 'vânăt', 'vârai', 'vâram', 'vârau', 'vârâi', 'vârâm', 'vârât',
  'vârșă', 'vâșca', 'vâșcă', 'vâște', 'vâști', 'văcar', 'vădan', 'vădit', 'văgaș', 'văile',
  'văleu', 'vălmi', 'vălug', 'vămii', 'văpăi', 'vărar', 'vărat', 'vărez', 'vărgi', 'văros',
  'vărsă', 'văsar', 'văsuț', 'vătaf', 'vătav', 'vătaș', 'văzui', 'văzut', 'walon', 'warez',
  'wații', 'weber', 'widia', 'widii', 'xenie', 'xenon', 'xerox', 'xifie', 'xilan', 'xilem',
  'xilen', 'xilon', 'xiloz', 'xismă', 'xterm', 'xviii', 'xxiii', 'xxvii', 'yogin', 'ytriu',
  'yucca', 'zabet', 'zabră', 'zacem', 'zadie', 'zahar', 'zaică', 'zaifă', 'zaimf', 'zaman',
  'zamca', 'zamcă', 'zapat', 'zapez', 'zapis', 'zaraf', 'zarif', 'zarpa', 'zbanț', 'zbate',
  'zbată', 'zbați', 'zbeng', 'zbici', 'zbier', 'zbilț', 'zbori', 'zburd', 'zbură', 'zbânț',
  'zbătu', 'zeama', 'zecar', 'zecea', 'zecer', 'zeche', 'zechi', 'zeghe', 'zeghi', 'zeiei',
  'zeină', 'zeire', 'zelar', 'zelos', 'zemii', 'zemos', 'zenda', 'zende', 'zendă', 'zenit',
  'zerar', 'zerit', 'zeros', 'zerou', 'zerul', 'zețaj', 'zețar', 'zgâit', 'zgăur', 'zicaș',
  'zidar', 'zidit', 'zigot', 'zilaș', 'zilei', 'ziler', 'zmeie', 'zmeoi', 'zmeul', 'zmeur',
  'zoaia', 'zoaie', 'zoană', 'zobit', 'zobon', 'zoile', 'zoios', 'zolit', 'zombi', 'zonaj',
  'zonal', 'zonar', 'zooid', 'zorea', 'zorit', 'zovon', 'zulie', 'zuluf', 'zulum', 'zulus',
  'zuluș', 'zurba', 'zurbă', 'zuzet', 'zuzui', 'zvânt', 'zvârl', 'zârnă', 'zâzâi', 'zăbun',
  'zăcaș', 'zăcea', 'zăcem', 'zăcui', 'zăcut', 'zădar', 'zăduf', 'zăduh', 'zăgan', 'zăgaz',
  'zăgaș', 'zăhat', 'zălar', 'zălog', 'zălud', 'zălug', 'zămci', 'zănat', 'zăpor', 'zăpuc',
  'zăpăi', 'zărar', 'zărit', 'zăton', 'zăuit', 'zăvat', 'zăvod', 'zăvoi', 'îmbia', 'îmbib',
  'îmbie', 'îmbii', 'îmbin', 'îmbuc', 'îmbăt', 'împac', 'împut', 'înalț', 'încap', 'încep',
  'încoa', 'încot', 'încui', 'încât', 'îndes', 'îndop', 'îndur', 'înfia', 'înfig', 'înfir',
  'înfoc', 'înfoi', 'înfăș', 'înfăț', 'îngop', 'îngân', 'înham', 'înhap', 'înhaț', 'înjug',
  'înjur', 'înmoi', 'înnod', 'înota', 'înotă', 'înoți', 'înpoi', 'însor', 'însul', 'întra',
  'întru', 'învia', 'învie', 'învii', 'învit', 'învăț', 'înșel', 'înșii', 'înșir', 'înțep',
  'înțes', 'ăleia', 'ălora', 'ăluia', 'ăstea', 'ăstei', 'ăstor', 'ăstui', 'ăuire', 'ăuită',
  'ăștia', 'șabac', 'șabăr', 'șacal', 'șafar', 'șahii', 'șahul', 'șaibă', 'șaica', 'șaică',
  'șaliu', 'șalău', 'șaman', 'șamoa', 'șamot', 'șanal', 'șapca', 'șapou', 'șaran', 'șarbă',
  'șarjă', 'șarlă', 'șasea', 'șasie', 'șasiu', 'șasla', 'șaten', 'șatră', 'șașiu', 'școli',
  'șeaua', 'ședei', 'ședem', 'șefie', 'șegii', 'șeiac', 'șeici', 'șeile', 'șelac', 'șelar',
  'șenaj', 'șenal', 'șepci', 'șerpi', 'șesar', 'șesos', 'șeuaș', 'șever', 'șevro', 'șezui',
  'șezut', 'șfanț', 'șiboi', 'șieși', 'șifon', 'șiism', 'șiită', 'șinar', 'șinor', 'șipcă',
  'șipot', 'șirag', 'șiruț', 'șitar', 'șivoi', 'șișcă', 'șișăi', 'șițar', 'șleah', 'șleau',
  'șlire', 'șnaps', 'șoadă', 'șocat', 'șodou', 'șofaj', 'șofat', 'șofez', 'șogor', 'șoldă',
  'șomaj', 'șomat', 'șomer', 'șomez', 'șontă', 'șopot', 'șopru', 'șotie', 'șovar', 'șovin',
  'șoșoi', 'șoșon', 'șpaga', 'șpago', 'șpagă', 'șpais', 'șpalt', 'șperț', 'șplit', 'șprat',
  'șpriț', 'șpăgi', 'ștaif', 'ștair', 'ștală', 'ștand', 'șteap', 'ștepi', 'șterg', 'șters',
  'șterț', 'șteze', 'știai', 'știam', 'știau', 'știft', 'știmă', 'știob', 'știrb', 'știui',
  'știut', 'știți', 'ștofă', 'ștraf', 'ștras', 'ștrec', 'ștric', 'ștrol', 'șturț', 'șuber',
  'șucar', 'șucoă', 'șufan', 'șugar', 'șuier', 'șuiet', 'șuieț', 'șuiță', 'șular', 'șuler',
  'șumar', 'șumen', 'șunăr', 'șurup', 'șustă', 'șutat', 'șuter', 'șutez', 'șutit', 'șutor',
  'șuvar', 'șvabă', 'șvarț', 'șvedă', 'șâșâi', 'șădea', 'șădem', 'șăgii', 'șăici', 'șăluț',
  'șăzui', 'șăzut', 'țaglă', 'țaică', 'țapap', 'țapin', 'țapoș', 'țapăn', 'țarat', 'țarca',
  'țarcă', 'țarna', 'țarnă', 'țeapa', 'țeapo', 'țeapă', 'țeară', 'țeasă', 'țeava', 'țeavo',
  'țepar', 'țepei', 'țepii', 'țepos', 'țesal', 'țesea', 'țesem', 'țeste', 'țesui', 'țesut',
  'țesăl', 'țevar', 'țevii', 'țevos', 'țiclă', 'țigan', 'țigâi', 'țiind', 'țimir', 'țipar',
  'țipat', 'țipet', 'țiplă', 'țipot', 'țipăt', 'țiuie', 'țiuit', 'țoabă', 'țoală', 'țoapă',
  'țocăi', 'țolet', 'țoluț', 'țucal', 'țucat', 'țugui', 'țuhal', 'țuică', 'țuluc', 'țurcă',
  'țușcă', 'țuști', 'țuțui', 'țuțul', 'țuțur', 'țâfnă', 'țâhlă', 'țâncă', 'țârfă', 'țâțos',
  'țâțâi', 'țăcăn', 'țăpoi', 'țăpuc', 'țărci', 'țărni', 'țărnă',
]

/** Every answer plus the wider dictionary — used to validate guesses (NFC). */
export const VALID_GUESSES: ReadonlySet<string> = new Set([...ANSWERS, ...EXTRA_GUESSES])

export const ANSWER_COUNT = ANSWERS.length
